'use strict';var f=!0,g=null,i=!1;JSON.Xa=function(a){var b={};try{0===a.indexOf("{")&&"}"===a.charAt(a.length-1)?b=JSON.parse(a):(console.log("first and last characters are not { and }. returning false"),b=i)}catch(c){alert("BAD JSON: "+a),console.error("CAUGHT ERROR! ->",c),b=i}return b};if("undefined"===typeof window||window===g)window={Q:{}};window.Q==g&&(window.Q={});if("undefined"===typeof twttr||twttr===g)twttr={};function k(a,b){b=b||"";"string"!==typeof a&&(a.global&&0>b.indexOf("g")&&(b+="g"),a.ignoreCase&&0>b.indexOf("i")&&(b+="i"),a.multiline&&0>b.indexOf("m")&&(b+="m"),a=a.source);return RegExp(a.replace(/#\{(\w+)\}/g,function(a,b){var e=twttr.a.b[b]||"";"string"!==typeof e&&(e=e.source);return e}),b)}
function l(a,b){return a.replace(/#\{(\w+)\}/g,function(a,d){return b[d]||""})}function n(a,b,c){var d=String.fromCharCode(b);c!==b&&(d+="-"+String.fromCharCode(c));a.push(d);return a}function p(a){var b={},c;for(c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b}function q(a,b,c){return!c?"string"===typeof a&&a.match(b)&&RegExp["$&"]===a:!a||a.match(b)&&RegExp["$&"]===a}twttr.a={};twttr.a.b={};var v={"&":"&amp;",">":"&gt;","<":"&lt;",'"':"&quot;","'":"&#39;"};
twttr.a.d=function(a){return a&&a.replace(/[&"'><]/g,function(a){return v[a]})};twttr.a.rb=k;twttr.a.ub=l;twttr.a.Ia=n;var w=String.fromCharCode,x=[w(32),w(133),w(160),w(5760),w(6158),w(8232),w(8233),w(8239),w(8287),w(12288)];n(x,9,13);n(x,8192,8202);var y=[w(65534),w(65279),w(65535)];n(y,8234,8238);twttr.a.b.tb=k(x.join(""));twttr.a.b.sb=k("["+x.join("")+"]");twttr.a.b.cb=k(y.join(""));twttr.a.b.qb=/\!'#%&'\(\)*\+,\\\-\.\/:;<=>\?@\[\]\^_{|}~\$/;var z=[];n(z,1024,1279);n(z,1280,1319);n(z,11744,11775);
n(z,42560,42655);n(z,1425,1471);n(z,1473,1474);n(z,1476,1477);n(z,1479,1479);n(z,1488,1514);n(z,1520,1524);n(z,64274,64296);n(z,64298,64310);n(z,64312,64316);n(z,64318,64318);n(z,64320,64321);n(z,64323,64324);n(z,64326,64335);n(z,1552,1562);n(z,1568,1631);n(z,1646,1747);n(z,1749,1756);n(z,1758,1768);n(z,1770,1775);n(z,1786,1788);n(z,1791,1791);n(z,1872,1919);n(z,2208,2208);n(z,2210,2220);n(z,2276,2302);n(z,64336,64433);n(z,64467,64829);n(z,64848,64911);n(z,64914,64967);n(z,65008,65019);
n(z,65136,65140);n(z,65142,65276);n(z,8204,8204);n(z,3585,3642);n(z,3648,3662);n(z,4352,4607);n(z,12592,12677);n(z,43360,43391);n(z,44032,55215);n(z,55216,55295);n(z,65441,65500);n(z,12449,12538);n(z,12540,12542);n(z,65382,65439);n(z,65392,65392);n(z,65296,65305);n(z,65313,65338);n(z,65345,65370);n(z,12353,12438);n(z,12441,12446);n(z,13312,19903);n(z,19968,40959);n(z,173824,177983);n(z,177984,178207);n(z,194560,195103);n(z,12291,12291);n(z,12293,12293);n(z,12347,12347);twttr.a.b.kb=k(z.join(""));
var B=[];n(B,192,214);n(B,216,246);n(B,248,255);n(B,256,591);n(B,595,596);n(B,598,599);n(B,601,601);n(B,603,603);n(B,611,611);n(B,616,616);n(B,623,623);n(B,626,626);n(B,649,649);n(B,651,651);n(B,699,699);n(B,768,879);n(B,7680,7935);twttr.a.b.ib=k(B.join(""));twttr.a.b.ba=/[#\uff03]/;twttr.a.b.Ya=k(/[a-z_#{latinAccentChars}#{nonLatinHashtagChars}]/i);twttr.a.b.Za=k(/[a-z0-9_#{latinAccentChars}#{nonLatinHashtagChars}]/i);twttr.a.b.T=k(/^(?:#{hashSigns}|:\/\/)/);twttr.a.b.$a=k(/(?:^|$|[^&a-z0-9_#{latinAccentChars}#{nonLatinHashtagChars}])/);
twttr.a.b.xa=k(/(#{hashtagBoundary})(#{hashSigns})(#{hashtagAlphaNumeric}*#{hashtagAlpha}#{hashtagAlphaNumeric}*)/gi);twttr.a.b.Hb=/(?:^|[^a-zA-Z0-9_!#$%&*@\uff20]|RT:?)/;twttr.a.b.s=/[@\uff20]/;twttr.a.b.ya=k("(#{validMentionPrecedingChars})(#{atSigns})([a-zA-Z0-9_]{1,20})(/[a-zA-Z][a-zA-Z0-9_-]{0,24})?","g");twttr.a.b.za=k(/^(?:#{spaces})*#{atSigns}([a-zA-Z0-9_]{1,20})/);twttr.a.b.A=k(/^(?:#{atSigns}|[#{latinAccentChars}]|:\/\/)/);twttr.a.b.Ob=k(/(?:[^A-Za-z0-9@\uff20$#\uff03#{invalid_chars_group}]|^)/);
twttr.a.b.da=/[-_.\/]$/;twttr.a.b.bb=l("#{punct}#{spaces_group}#{invalid_chars_group}",twttr.a.b);twttr.a.b.Db=k(/[^#{invalidDomainChars}]/);twttr.a.b.Kb=k(/(?:(?:#{validDomainChars}(?:[_-]|#{validDomainChars})*)?#{validDomainChars}\.)/);twttr.a.b.Eb=k(/(?:(?:#{validDomainChars}(?:-|#{validDomainChars})*)?#{validDomainChars}\.)/);twttr.a.b.Fb=k(/(?:(?:aero|asia|biz|cat|com|coop|edu|gov|info|int|jobs|mil|mobi|museum|name|net|org|pro|tel|travel|xxx)(?=[^0-9a-zA-Z]|$))/);twttr.a.b.Bb=k(/(?:(?:ac|ad|ae|af|ag|ai|al|am|an|ao|aq|ar|as|at|au|aw|ax|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bm|bn|bo|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cs|cu|cv|cx|cy|cz|dd|de|dj|dk|dm|do|dz|ec|ee|eg|eh|er|es|et|eu|fi|fj|fk|fm|fo|fr|ga|gb|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kp|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|me|mg|mh|mk|ml|mm|mn|mo|mp|mq|mr|ms|mt|mu|mv|mw|mx|my|mz|na|nc|ne|nf|ng|ni|nl|no|np|nr|nu|nz|om|pa|pe|pf|pg|ph|pk|pl|pm|pn|pr|ps|pt|pw|py|qa|re|ro|rs|ru|rw|sa|sb|sc|sd|se|sg|sh|si|sj|sk|sl|sm|sn|so|sr|ss|st|su|sv|sy|sz|tc|td|tf|tg|th|tj|tk|tl|tm|tn|to|tp|tr|tt|tv|tw|tz|ua|ug|uk|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|ye|yt|za|zm|zw)(?=[^0-9a-zA-Z]|$))/);
twttr.a.b.Jb=k(/(?:xn--[0-9a-z]+)/);twttr.a.b.Cb=k(/(?:#{validSubdomain}*#{validDomainName}(?:#{validGTLD}|#{validCCTLD}|#{validPunycode}))/);twttr.a.b.va=k(/(?:(?:[a-z0-9#{latinAccentChars}]+)\.)+(?:#{validGTLD}|#{validCCTLD}|#{validPunycode})/gi);twttr.a.b.ca=k(/^#{validDomainName}#{validCCTLD}$/);twttr.a.b.Ib=k(/[0-9]+/);twttr.a.b.Gb=k(/[a-z0-9!\*';:=\+,\.\$\/%#\[\]\-_~|&#{latinAccentChars}]/i);twttr.a.b.Lb=k(/\(#{validGeneralUrlPathChars}+\)/i);twttr.a.b.Nb=k(/[\+\-a-z0-9=_#\/#{latinAccentChars}]|(?:#{validUrlBalancedParens})/i);
twttr.a.b.Mb=k("(?:(?:#{validGeneralUrlPathChars}*(?:#{validUrlBalancedParens}#{validGeneralUrlPathChars}*)*#{validUrlPathEndingChars})|(?:@#{validGeneralUrlPathChars}+/))","i");twttr.a.b.Pb=/[a-z0-9!?\*'\(\);:&=\+\$\/%#\[\]\-_\.,~|]/i;twttr.a.b.Qb=/[a-z0-9_&=#\/]/i;twttr.a.b.B=k("((#{validUrlPrecedingChars})((https?:\\/\\/)?(#{validDomain})(?::(#{validPortNumber}))?(\\/#{validUrlPath}*)?(\\?#{validUrlQueryChars}*#{validUrlQueryEndingChars})?))","gi");twttr.a.b.Aa=/^https?:\/\/t\.co\/[a-z0-9]+/i;
twttr.a.b.k=/[a-z]{1,6}(?:[._][a-z]{1,2})?/i;twttr.a.b.wa=k("(^|#{spaces})(\\$)(#{cashtag})(?=$|\\s|[#{punct}])","gi");twttr.a.b.ic=/[a-z0-9\-._~]/i;twttr.a.b.$b=/(?:%[0-9a-f]{2})/i;twttr.a.b.bc=/[!$&'()*+,;=]/i;twttr.a.b.Zb=k("(?:#{validateUrlUnreserved}|#{validateUrlPctEncoded}|#{validateUrlSubDelims}|[:|@])","i");twttr.a.b.Fa=/(?:[a-z][a-z0-9+\-.]*)/i;twttr.a.b.jc=k("(?:#{validateUrlUnreserved}|#{validateUrlPctEncoded}|#{validateUrlSubDelims}|:)*","i");twttr.a.b.Rb=/(?:[0-9]|(?:[1-9][0-9])|(?:1[0-9]{2})|(?:2[0-4][0-9])|(?:25[0-5]))/i;
twttr.a.b.Xb=k(/(?:#{validateUrlDecOctet}(?:\.#{validateUrlDecOctet}){3})/i);twttr.a.b.Yb=/(?:\[[a-f0-9:\.]+\])/i;twttr.a.b.Wb=k("(?:#{validateUrlIpv4}|#{validateUrlIpv6})","i");twttr.a.b.cc=/(?:[a-z0-9](?:[a-z0-9_\-]*[a-z0-9])?)/i;twttr.a.b.Tb=/(?:[a-z0-9](?:[a-z0-9\-]*[a-z0-9])?)/i;twttr.a.b.Ub=/(?:[a-z](?:[a-z0-9\-]*[a-z0-9])?)/i;twttr.a.b.Sb=k(/(?:(?:#{validateUrlSubDomainSegment]}\.)*(?:#{validateUrlDomainSegment]}\.)#{validateUrlDomainTld})/i);
twttr.a.b.Vb=k("(?:#{validateUrlIp}|#{validateUrlDomain})","i");twttr.a.b.hc=/(?:(?:[a-z0-9]|[^\u0000-\u007f])(?:(?:[a-z0-9_\-]|[^\u0000-\u007f])*(?:[a-z0-9]|[^\u0000-\u007f]))?)/i;twttr.a.b.ec=/(?:(?:[a-z0-9]|[^\u0000-\u007f])(?:(?:[a-z0-9\-]|[^\u0000-\u007f])*(?:[a-z0-9]|[^\u0000-\u007f]))?)/i;twttr.a.b.fc=/(?:(?:[a-z]|[^\u0000-\u007f])(?:(?:[a-z0-9\-]|[^\u0000-\u007f])*(?:[a-z0-9]|[^\u0000-\u007f]))?)/i;twttr.a.b.dc=k(/(?:(?:#{validateUrlUnicodeSubDomainSegment}\.)*(?:#{validateUrlUnicodeDomainSegment}\.)#{validateUrlUnicodeDomainTld})/i);
twttr.a.b.gc=k("(?:#{validateUrlIp}|#{validateUrlUnicodeDomain})","i");twttr.a.b.ac=/[0-9]{1,5}/;twttr.a.b.Ha=k("(?:(#{validateUrlUserinfo})@)?(#{validateUrlUnicodeHost})(?::(#{validateUrlPort}))?","i");twttr.a.b.Ba=k("(?:(#{validateUrlUserinfo})@)?(#{validateUrlHost})(?::(#{validateUrlPort}))?","i");twttr.a.b.Da=k(/(\/#{validateUrlPchar}*)*/i);twttr.a.b.Ea=k(/(#{validateUrlPchar}|\/|\?)*/i);twttr.a.b.Ca=k(/(#{validateUrlPchar}|\/|\?)*/i);
twttr.a.b.Ga=k("^(?:([^:/?#]+):\\/\\/)?([^/?#]*)([^?#]*)(?:\\?([^#]*))?(?:#(.*))?$","i");
var C={urlClass:f,listClass:f,usernameClass:f,hashtagClass:f,cashtagClass:f,usernameUrlBase:f,listUrlBase:f,hashtagUrlBase:f,cashtagUrlBase:f,usernameUrlBlock:f,listUrlBlock:f,hashtagUrlBlock:f,linkUrlBlock:f,usernameIncludeSymbol:f,suppressLists:f,suppressNoFollow:f,suppressDataScreenName:f,urlEntities:f,symbolTag:f,textWithSymbolTag:f,urlTarget:f,invisibleTagAttrs:f,linkAttributeBlock:f,linkTextBlock:f},E={disabled:f,readonly:f,multiple:f,checked:f};
twttr.a.sa=function(a){var b="",c;for(c in a){var d=a[c];E[c]&&(d=d?c:g);d!=g&&(b+=" "+twttr.a.d(c)+'="'+twttr.a.d(d.toString())+'"')}return b};twttr.a.p=function(a,b,c,d){d.xb||(c.rel="nofollow");d.ga&&d.ga(a,c);d.ha&&(b=d.ha(a,b));a={text:b,Ka:twttr.a.sa(c)};return l("<a#{attr}>#{text}</a>",a)};twttr.a.q=function(a,b,c,d,e){var h=e.O?"<"+e.O+">"+b+"</"+e.O+">":b,c=twttr.a.d(c),c=e.P?"<"+e.P+">"+c+"</"+e.P+">":c;return e.Ab||!b.match(twttr.a.b.s)?twttr.a.p(a,h+c,d,e):h+twttr.a.p(a,c,d,e)};
twttr.a.ka=function(a,b,c){var b=b.substring(a.c[0],a.c[0]+1),d=twttr.a.d(a.j),e=p(c.l||{});e.href=c.G+d;e.title="#"+d;e["class"]=c.F;return twttr.a.q(a,b,d,e,c)};twttr.a.ja=function(a,b){var c=twttr.a.d(a.k),d=p(b.l||{});d.href=b.u+c;d.title="$"+c;d["class"]=b.t;return twttr.a.q(a,"$",c,d,b)};
twttr.a.la=function(a,b,c){var b=b.substring(a.c[0],a.c[0]+1),d=twttr.a.d(a.g),e=twttr.a.d(a.r),h=a.r&&!c.wb,j=p(c.l||{});j["class"]=h?c.J:c.R;j.href=h?c.K+d+e:c.S+d;!h&&!c.vb&&(j["data-screen-name"]=d);return twttr.a.q(a,b,h?d+e:d,j,c)};twttr.a.ma=function(a,b){var c=a.url,d=twttr.a.d(c),e=b.h&&b.h[c]||a;e.z&&(d=twttr.a.ia(e,b));var h=p(b.l||{});h.href=c;b.ta&&(h["class"]=b.ta);b.ua&&(h.target=b.ua);!b.title&&e.z&&(h.title=e.U);return twttr.a.p(a,d,h,b)};
twttr.a.ia=function(a,b){var c=a.z,d=a.U,e=c.replace(/\u2026/g,"");if(-1!=d.indexOf(e)){var h=d.indexOf(e),c={Sa:e,Ra:d.substr(0,h),Ja:d.substr(h+e.length),pb:c.match(/^\u2026/)?"\u2026":"",Wa:c.match(/\u2026$/)?"\u2026":""},j;for(j in c)c.hasOwnProperty(j)&&(c[j]=twttr.a.d(c[j]));c.invisible=b.H;return l("<span class='tco-ellipsis'>#{precedingEllipsis}<span #{invisible}>&nbsp;</span></span><span #{invisible}>#{beforeDisplayUrl}</span><span class='js-display-url'>#{displayUrlSansEllipses}</span><span #{invisible}>#{afterDisplayUrl}</span><span class='tco-ellipsis'><span #{invisible}>&nbsp;</span>#{followingEllipsis}</span>",
c)}return c};
twttr.a.e=function(a,b,c){c=p(c||{});c.F=c.F||"tweet-url hashtag";c.G=c.G||"https://twitter.com/#!/search?q=%23";c.t=c.t||"tweet-url cashtag";c.u=c.u||"https://twitter.com/#!/search?q=%24";c.J=c.J||"tweet-url list-slug";c.R=c.R||"tweet-url username";c.S=c.S||"https://twitter.com/";c.K=c.K||"https://twitter.com/";c.l=twttr.a.Y(c);c.H=c.H||"style='position:absolute;left:-9999px;'";var d,e,h;if(c.h){d={};e=0;for(h=c.h.length;e<h;e++)d[c.h[e].url]=c.h[e];c.h=d}d="";h=0;b.sort(function(a,b){return a.c[0]-
b.c[0]});for(e=0;e<b.length;e++){var j=b[e];d+=a.substring(h,j.c[0]);j.url?d+=twttr.a.ma(j,c):j.j?d+=twttr.a.ka(j,a,c):j.g?d+=twttr.a.la(j,a,c):j.k&&(d+=twttr.a.ja(j,c));h=j.c[1]}return d+=a.substring(h,a.length)};twttr.a.Qa=function(a,b,c){var d=[],e;for(e in b)d=d.concat(b[e]);for(b=0;b<d.length;b++)entity=d[b],entity.oa?entity.g=entity.oa:entity.text&&(entity.j=entity.text);twttr.a.na(a,d);return twttr.a.e(a,d,c)};
twttr.a.Y=function(a){var b={},c;for(c in a){var d=a[c];C[c]||(E[c]&&(d=d?c:g),d!=g&&(b[c]=d))}return b};twttr.a.La=function(a,b){var c=twttr.a.W(a);return twttr.a.e(a,c,b)};twttr.a.Pa=function(a,b){var c=twttr.a.o(a);return twttr.a.e(a,c,b)};twttr.a.Na=function(a,b){var c=twttr.a.n(a);return twttr.a.e(a,c,b)};twttr.a.Ma=function(a,b){var c=twttr.a.m(a);return twttr.a.e(a,c,b)};twttr.a.Oa=function(a,b){var c=twttr.a.i(a,{aa:i});return twttr.a.e(a,c,b)};
twttr.a.L=function(a){a.sort(function(a,b){return a.c[0]-b.c[0]});for(var b=a[0],c=1;c<a.length;c++)b.c[1]>a[c].c[0]?(a.splice(c,1),c--):b=a[c]};twttr.a.W=function(a){a=twttr.a.i(a,{aa:i}).concat(twttr.a.o(a)).concat(twttr.a.n(a,{v:i})).concat(twttr.a.m(a));if(0==a.length)return[];twttr.a.L(a);return a};twttr.a.Z=function(a){for(var b=[],a=twttr.a.$(a),c=0;c<a.length;c++)b.push(a[c].g);return b};
twttr.a.$=function(a){for(var b=[],a=twttr.a.o(a),c=0;c<a.length;c++)mentionOrList=a[c],""==mentionOrList.r&&b.push({g:mentionOrList.g,c:mentionOrList.c});return b};twttr.a.o=function(a){if(!a||!a.match(twttr.a.b.s))return[];var b=[];a.replace(twttr.a.b.ya,function(a,d,e,h,j,m,s){s.slice(m+a.length).match(twttr.a.b.A)||(j=j||"",a=m+d.length,b.push({g:h,r:j,c:[a,a+h.length+j.length+1]}))});return b};
twttr.a.Ua=function(a){if(!a)return g;a=a.match(twttr.a.b.za);return!a||RegExp.rightContext.match(twttr.a.b.A)?g:a[1]};twttr.a.Va=function(a,b){for(var c=[],d=twttr.a.i(a,b),e=0;e<d.length;e++)c.push(d[e].url);return c};
twttr.a.i=function(a,b){b||(b={C:f});if(!a||(b.C?!a.match(/\./):!a.match(/:/)))return[];for(var c=[];twttr.a.b.B.exec(a);){var d=RegExp.$2,e=RegExp.$3,h=RegExp.$5,j=RegExp.$7,m=twttr.a.b.B.lastIndex,s=m-e.length;if(RegExp.$4)e.match(twttr.a.b.Aa)&&(e=RegExp.lastMatch,m=s+e.length),c.push({url:e,c:[s,m]});else if(b.C&&!d.match(twttr.a.b.da)){var r=g,t=i,u=0;h.replace(twttr.a.b.va,function(a){var b=h.indexOf(a,u);u=b+a.length;r={url:a,c:[s+b,s+u]};(t=a.match(twttr.a.b.ca))||c.push(r)});r!=g&&j&&(t&&
c.push(r),r.url=e.replace(h,r.url),r.c[1]=m)}}return c};twttr.a.X=function(a){for(var b=[],a=twttr.a.n(a),c=0;c<a.length;c++)b.push(a[c].j);return b};twttr.a.n=function(a,b){b||(b={v:f});if(!a||!a.match(twttr.a.b.ba))return[];var c=[];a.replace(twttr.a.b.xa,function(a,b,d,e,r,t){t.slice(r+a.length).match(twttr.a.b.T)||(a=r+b.length,c.push({j:e,c:[a,a+e.length+1]}))});if(b.v){var d=twttr.a.i(a);if(0<d.length){d=c.concat(d);twttr.a.L(d);for(var c=[],e=0;e<d.length;e++)d[e].j&&c.push(d[e])}}return c};
twttr.a.Ta=function(a){for(var b=[],a=twttr.a.m(a),c=0;c<a.length;c++)b.push(a[c].k);return b};twttr.a.m=function(a){if(!a||-1==a.indexOf("$"))return[];var b=[];a.replace(twttr.a.b.wa,function(a,d,e,h,j){a=j+d.length;b.push({k:h,c:[a,a+h.length+1]})});return b};twttr.a.na=function(a,b){twttr.a.w(a,b,i)};twttr.a.jb=function(a,b){twttr.a.w(a,b,f)};
twttr.a.w=function(a,b,c){if(0!=b.length){var d=0,e=0;b.sort(function(a,b){return a.c[0]-b.c[0]});for(var h=0,j=b[0];d<a.length;){if(j.c[0]==(c?d:e)){var m=j.c[1]-j.c[0];j.c[0]=c?e:d;j.c[1]=j.c[0]+m;h++;if(h==b.length)break;j=b[h]}m=a.charCodeAt(d);55296<=m&&(56319>=m&&d<a.length-1)&&(m=a.charCodeAt(d+1),56320<=m&&57343>=m&&d++);e++;d++}}};twttr.a.ra=function(a){for(var a=a.split("<"),b,c=[],d=0;d<a.length;d+=1)if(b=a[d]){b=b.split(">");for(var e=0;e<b.length;e+=1)c.push(b[e])}else c.push("");return c};
twttr.a.ab=function(a,b,c){b=b||[];c=c||{};if(0===b.length)return a;var c=c.zb||"em",c=["<"+c+">","</"+c+">"],a=twttr.a.ra(a),d,e,h="",j=0,m=a[0],s=0,r=0,t=i,u=m,D=[],A;for(d=0;d<b.length;d+=1)for(e=0;e<b[d].length;e+=1)D.push(b[d][e]);for(b=0;b<D.length;b+=1){e=D[b];d=c[b%2];for(A=i;m!=g&&e>=s+m.length;)h+=u.slice(r),t&&e===s+u.length&&(h+=d,A=f),a[j+1]&&(h+="<"+a[j+1]+">"),s+=u.length,r=0,j+=2,u=m=a[j],t=i;!A&&m!=g?(t=e-s,h+=u.slice(r,t)+d,r=t,t=0===b%2?f:i):A||(h+=d)}if(m!=g){r<u.length&&(h+=u.slice(r));
for(b=j+1;b<a.length;b+=1)h+=0===b%2?a[b]:"<"+a[b]+">"}return h};var F=[w(65534),w(65279),w(65535),w(8234),w(8235),w(8236),w(8237),w(8238)];twttr.a.D=function(a){var b;b||(b={pa:20,qa:21});for(var c=a.length,a=twttr.a.i(a),d=0;d<a.length;d++)c+=a[d].c[0]-a[d].c[1],c=a[d].url.toLowerCase().match(/^https:\/\//)?c+b.qa:c+b.pa;return c};twttr.a.ea=function(a){if(!a)return"empty";if(140<twttr.a.D(a))return"too_long";for(var b=0;b<F.length;b++)if(0<=a.indexOf(F[b]))return"invalid_characters";return i};
twttr.a.fa=function(a){return!twttr.a.ea(a)};twttr.a.hb=function(a){if(!a)return i;var b=twttr.a.Z(a);return 1===b.length&&b[0]===a.slice(1)};var G=k(/^#{validMentionOrList}$/);twttr.a.fb=function(a){a=a.match(G);return!(!a||!(""==a[1]&&a[4]))};twttr.a.eb=function(a){if(!a)return i;var b=twttr.a.X(a);return 1===b.length&&b[0]===a.slice(1)};
twttr.a.gb=function(a,b,c){b==g&&(b=f);c==g&&(c=f);if(!a)return i;var d=a.match(twttr.a.b.Ga);if(!d||d[0]!==a)return i;var a=d[1],e=d[2],h=d[3],j=d[4],d=d[5];return c&&(!q(a,twttr.a.b.Fa)||!a.match(/^https?$/i))||!q(h,twttr.a.b.Da)||!q(j,twttr.a.b.Ea,f)||!q(d,twttr.a.b.Ca,f)?i:b&&q(e,twttr.a.b.Ha)||!b&&q(e,twttr.a.b.Ba)};"undefined"!=typeof module&&module.V&&(module.V=twttr.a);try{var H=i,I,J;chrome.f.nb.addListener(function(a){twttr.a.fa(a)&&(H=a,I&&K("tweetEntered"),console.log("tweet:"+a))});chrome.f.N({description:"Tweet: %s"});chrome.f.ob.addListener(function(){var a=new XMLHttpRequest;a.open("GET","https://twitter.com",f);a.onreadystatechange=function(){var b,c=a.responseText;c&&(b=c.indexOf('name="authenticity_token"'));c&&-1<b&&(b=c.substring(0,b),I=b.substring(b.lastIndexOf('value="')+7,b.lastIndexOf('"')),console.log("authToken:"+I),H&&K("xhr"),a.abort())};console.log("onInputStarted, request authToken");
a.send()});chrome.f.mb.addListener(function(a){100<a.length&&100<twttr.a.D(a)?chrome.f.N({description:"Tweet ("+a.length+"): %s"}):chrome.f.N({description:"Tweet: %s"})});var K=function(a){var b=H,c=I;J=new XMLHttpRequest;J.open("POST","https://twitter.com/i/tweet/create",f);J.onreadystatechange=function(){if(4===J.readyState){var c="xhr"===a?" from xhr!":"";if(200===J.status)alert("Successfully posted tweet"+c);else{c=f;try{var e=document.createElement("div");e.contentEditable=f;document.body.appendChild(e);
e.innerHTML=b;e.unselectable="off";e.focus();document.execCommand("SelectAll");document.execCommand("Copy",i,g);document.body.removeChild(e);c=i;alert("Your tweet failed to post, so we copied it to your clipboard.")}catch(h){}chrome.yb.create({url:"https://twitter.com/"+(c?"":"#"+b)})}J.abort();J=g}};J.setRequestHeader("Content-type","application/x-www-form-urlencoded");J.send("status="+b+"&place_id=&authenticity_token="+c);b=i};chrome.f.lb.addListener(function(){H=i;J&&J.abort()});console.log("loaded")}catch(L){throw alert("lastError:"+
(chrome.M.I?chrome.M.I.message:"")),console.error("lastError object:",chrome.M.I),L;};
